ALTER TABLE OST_BUCKET ADD CONSTRAINT PK_OST_BUCKET PRIMARY KEY (ID) USING INDEX PK_OST_BUCKET;

ALTER TABLE OST_BUCKET ADD CONSTRAINT UK_OST_BUCKET_NAME UNIQUE (NAME) USING INDEX UK_OST_BUCKET_NAME;
