ALTER TABLE OST_OBJECT ADD CONSTRAINT FK_OST_OBJECT_BUCKET FOREIGN KEY (BUCKET_ID) REFERENCES OST_BUCKET (ID);

ALTER TABLE OST_OBJECT_METADATA ADD CONSTRAINT FK_OST_OBJECT_METADATA_OBJECT FOREIGN KEY (OBJECT_ID) REFERENCES OST_OBJECT (ID);