ALTER TABLE OST_OBJECT ADD CONSTRAINT PK_OST_OBJECT PRIMARY KEY (ID) USING INDEX PK_OST_OBJECT;

ALTER TABLE OST_OBJECT ADD CONSTRAINT UK_OST_OBJECT_BUCKET_KEY UNIQUE (BUCKET_ID, OBJECT_KEY) USING INDEX UK_OST_OBJECT_BUCKET_KEY;

ALTER TABLE OST_OBJECT_METADATA ADD CONSTRAINT PK_OST_OBJECT_METADATA PRIMARY KEY (OBJECT_ID, NAME) USING INDEX PK_OST_OBJECT_METADATA;

ALTER TABLE OST_BLOB_PURGE ADD CONSTRAINT PK_OST_BLOB_PURGE PRIMARY KEY (ID) USING INDEX PK_OST_BLOB_PURGE;