ALTER TABLE OST_OBJECT RENAME COLUMN OBJECT_KEY TO OBJECT_NAME;

ALTER TABLE OST_OBJECT MODIFY (OBJECT_NAME NULL);

ALTER TABLE OST_OBJECT ADD (UPDATED_AT TIMESTAMP WITH TIME ZONE);

UPDATE OST_OBJECT SET UPDATED_AT = CREATED_AT;

ALTER TABLE OST_OBJECT MODIFY (UPDATED_AT NOT NULL);