ALTER TABLE OST_TRANSACTION ADD CONSTRAINT CK_OST_TRANSACTION_STATUS CHECK (STATUS IN ('OPEN', 'COMMITTED', 'ROLLED_BACK', 'EXPIRED'));

ALTER TABLE OST_OBJECT ADD CONSTRAINT CK_OST_OBJECT_STATUS CHECK (STATUS IN ('PENDING', 'ACTIVE'));