ALTER TABLE OST_TRANSACTION ADD CONSTRAINT PK_OST_TRANSACTION PRIMARY KEY (ID) USING INDEX PK_OST_TRANSACTION;

ALTER TABLE OST_OBJECT ADD CONSTRAINT UK_OST_OBJECT_REPLACES UNIQUE (REPLACES_OBJECT_ID) USING INDEX UK_OST_OBJECT_REPLACES;