ALTER TABLE OST_OBJECT ADD CONSTRAINT PK_OST_OBJECT PRIMARY KEY USING INDEX PK_OST_OBJECT;

ALTER TABLE OST_OBJECT ADD CONSTRAINT UK_OST_OBJECT_BUCKET_KEY UNIQUE USING INDEX UK_OST_OBJECT_BUCKET_KEY;

ALTER TABLE OST_OBJECT_METADATA ADD CONSTRAINT PK_OST_OBJECT_METADATA PRIMARY KEY USING INDEX PK_OST_OBJECT_METADATA;

ALTER TABLE OST_BLOB_PURGE ADD CONSTRAINT PK_OST_BLOB_PURGE PRIMARY KEY USING INDEX PK_OST_BLOB_PURGE;