CREATE UNIQUE INDEX PK_OST_OBJECT ON OST_OBJECT (ID);

-- Unicité d'une clé dans un bucket ; sert aussi l'index de la FK BUCKET_ID et la pagination par clé.
CREATE UNIQUE INDEX UK_OST_OBJECT_BUCKET_KEY ON OST_OBJECT (BUCKET_ID, OBJECT_KEY);

-- Colonne de tête = FK OBJECT_ID.
CREATE UNIQUE INDEX PK_OST_OBJECT_METADATA ON OST_OBJECT_METADATA (OBJECT_ID, NAME);

CREATE UNIQUE INDEX PK_OST_BLOB_PURGE ON OST_BLOB_PURGE (ID);

-- Sélection des blobs échus par le job de purge.
CREATE INDEX IX_OST_BLOB_PURGE_NOT_BEFORE ON OST_BLOB_PURGE (NOT_BEFORE);