ALTER TABLE OST_OBJECT RENAME COLUMN OBJECT_KEY TO OBJECT_NAME;

ALTER TABLE OST_OBJECT ALTER COLUMN OBJECT_NAME DROP NOT NULL;

ALTER TABLE OST_OBJECT ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;

UPDATE OST_OBJECT SET UPDATED_AT = CREATED_AT;

ALTER TABLE OST_OBJECT ALTER COLUMN UPDATED_AT SET NOT NULL;