ALTER TABLE OST_TRANSACTION ADD CONSTRAINT PK_OST_TRANSACTION PRIMARY KEY USING INDEX PK_OST_TRANSACTION;

ALTER TABLE OST_OBJECT ADD CONSTRAINT UK_OST_OBJECT_REPLACES UNIQUE USING INDEX UK_OST_OBJECT_REPLACES;