ALTER TABLE OST_OBJECT ADD CONSTRAINT FK_OST_OBJECT_TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES OST_TRANSACTION (ID);

ALTER TABLE OST_OBJECT ADD CONSTRAINT FK_OST_OBJECT_REPLACES FOREIGN KEY (REPLACES_OBJECT_ID) REFERENCES OST_OBJECT (ID);