<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.doriangrelu</groupId>
        <artifactId>ostore-drivers</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>ostore-driver-s3</artifactId>
    <name>OStore :: drivers :: s3</name>
    <description>Amazon S3 (and compatible) storage driver.</description>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ostore-driver-spi</artifactId>
        </dependency>
    </dependencies>
</project>
